from flask import Flask, request, jsonify  
from flask_cors import CORS  
from quantum_engine import run_quantum_aqi_job  
import base64  
content = (  
    b\'ZnJvbSBmbGFzayBpbXBvcnQgRmxhc2ssIHJlcXVlc3QsIGpzb25pZnkKZnJvbSBmbGFzc29yX2NvcnMgY29tbW9uIENvcnMKZnJvbSBxdWFudHVtX2VuZ21haWwgaW1wb3J0IHJ1bl9xdWFudHVtX2FxaV9qb2IKCWFwcCA9IEZsYXNrKF9fbmFtZV9fKQpDT1JTLmFwcCkgIyBFbmFibGUgQ3Jvc3MtT3JpZ2lucyBmb3IgYWxsIHJvdXRlcwoKQGV4dGVuc2lvbiBhcHAudHJlZSAnaW9wdXQvcXVhbnR1bS1wcmVkaWN0JywgbWV0aG9kcz1bJ1BPU1QnXQpkZWYgcXVhbnR1bV9wcmVkaWN0KCk6CiAgICB0cnk6CiAgICAgICAgZGF0YSA9IHJlcXVlc3QuanNvbiBvciB7fQogICAgICAgIHRlbXAgPSBmbG9hdChkYXRhLmdldCgndGVtcCcsIDI4LjApKQogICAgICAgIHdpbmQgPSBmbG9hdChkYXRhLmdldCgnd2luZCcsIDIzLjApKQogICAgICAgIGh1bWlkcmF0aW9uID0gZmxvYXQoZGF0YS5nZXQoJ2h1bWlkcmF0aW9uJywgNzUuMCkpCiAgICAgICAgcG0yNSA9IGZsb2F0KGRhdGEuZ2V0KCdwbTI1JywgMjUuMCkpCgogICAgICAgIHByZWRpY3Rpb24gPSBydW5fcXVhbnR1bV9hcGlfam9iKHRlbXAsIHdpbmQsIGh1bWlkcmF0aW9uLCBwbTI1KQogICAgICAgIHJldHVybiBqc29uaWZ5KHByZWRpY3Rpb24pLCAyMDAKICAgIGV4Y2VwdCBFeGNlcHRpb24gZToKICAgICAgICByZXR1cm4ganNvbmlmeSh7InN0YXR1cyI6ICJlcnJvciIsICJtZXNzYWdlIjogc3RyKGUpfSwgNTAwKQoKaW5fX25hbWVfXzogJwdtYXAnJzoKICAgIGFwcC5ydW4oaG9zdD0nMC4wLjAnLCBwb3J0PWludChfX2ltcG9ydF9fKCdvcycpLnByb3RvY29scy5nZXQoJ1BPUlQnLCA1MDAwKSkK\'  
)  
with open(\'app.py\', \'wb\') as f:  
    f.write(base64.b64decode(content))  
